set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sb_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sa_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sw_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[0]}]
set_property PACKAGE_PIN A3 [get_ports {Red[0]}]
set_property PACKAGE_PIN B4 [get_ports {Red[1]}]
set_property PACKAGE_PIN C5 [get_ports {Red[2]}]
set_property PACKAGE_PIN A4 [get_ports {Red[3]}]
set_property PACKAGE_PIN C6 [get_ports {Green[0]}]
set_property PACKAGE_PIN A5 [get_ports {Green[1]}]
set_property PACKAGE_PIN B6 [get_ports {Green[2]}]
set_property PACKAGE_PIN A6 [get_ports {Green[3]}]
set_property PACKAGE_PIN B7 [get_ports {Blue[0]}]
set_property PACKAGE_PIN C7 [get_ports {Blue[1]}]
set_property PACKAGE_PIN D7 [get_ports {Blue[2]}]
set_property PACKAGE_PIN D8 [get_ports {Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property PACKAGE_PIN B11 [get_ports hs]
set_property PACKAGE_PIN B12 [get_ports vs]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports sa]
set_property IOSTANDARD LVCMOS33 [get_ports sw]
set_property IOSTANDARD LVCMOS33 [get_ports sb]
set_property PACKAGE_PIN G17 [get_ports sw]
set_property PACKAGE_PIN D18 [get_ports sa]
set_property PACKAGE_PIN E18 [get_ports sb]

set_property IOSTANDARD LVCMOS33 [get_ports left_test]
set_property PACKAGE_PIN H17 [get_ports left_test]
set_property IOSTANDARD LVCMOS33 [get_ports right_test]
set_property PACKAGE_PIN K15 [get_ports right_test]


set_property IOSTANDARD LVCMOS33 [get_ports {filter_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {filter_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {frequency_rate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {frequency_rate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports frequency]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN E16 [get_ports {filter_out[1]}]
set_property PACKAGE_PIN F13 [get_ports {filter_out[0]}]
set_property PACKAGE_PIN G13 [get_ports {frequency_rate[1]}]
set_property PACKAGE_PIN H16 [get_ports {frequency_rate[0]}]
set_property PACKAGE_PIN F16 [get_ports frequency]
set_property PACKAGE_PIN D14 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports sig]
set_property PACKAGE_PIN J15 [get_ports sig]